### ISSUE TITLE
LIBXML_ICU_ENABLED is not defined in RPM build

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/libxml2-os2#2]
This is a simple configure test case from chromium that fails and doesn't let us use the system libxml2 build:
```c
#include <libxml/xmlversion.h>
#if !defined(LIBXML_ICU_ENABLED)
#error "libxml icu not enabled"
#endif

int main(int argc, char **argv)
{
}
```
Needed for https://github.com/bitwiseworks/qtwebengine-chromium-os2/issues/3.

**Comment by dmik** [comment]
From what I see in `configure.ac`, libxml2 needs `--with-icu` to get this define (and ICU support) enabled. Should be easily fixable.

**Comment by SilvanScherrer** [comment]
This is fixed with the next rpm. It will be uploaded within 1 hour.
